#!/bin/bash
# ===== 快速验证命令集 =====
# 用于逐步验证邮件认证系统的关键功能

echo "🔧 邮件认证系统快速验证命令"
echo "=================================="

# ===== 1. 基础环境检查 =====
echo -e "\n📋 1. 基础环境检查"
echo "执行以下命令检查环境："
echo ""
echo "# 检查Python和依赖"
echo "python3 --version"
echo "python3 -c 'import smtplib, poplib, email, flask, flask_cors; print(\"✅ 所有依赖已安装\")'"
echo ""
echo "# 检查文件结构"
echo "ls -la client/login/"
echo "ls -la cloudserver/login/"
echo ""

# ===== 2. 配置验证 =====
echo -e "\n⚙️ 2. 配置验证"
echo "执行以下命令验证配置："
echo ""
echo "# 检查邮件配置"
echo "cd client/login && python3 -c 'from email_client import CLIENT_EMAIL, SERVER_EMAIL; print(f\"客户端: {CLIENT_EMAIL}, 服务器: {SERVER_EMAIL}\")'"
echo ""
echo "# 检查加密功能"
echo "cd cloudserver/login && python3 -c 'from crypto_utils import convert_plaintext_to_encrypted; print(f\"加密测试: {convert_plaintext_to_encrypted(\"test123\")}\")'"
echo ""

# ===== 3. 独立组件测试 =====
echo -e "\n🔧 3. 独立组件测试"
echo "执行以下命令测试各组件："
echo ""
echo "# 测试客户端邮件模块（10秒后自动退出）"
echo "cd client/login && timeout 10s python3 email_client.py"
echo ""
echo "# 测试服务器端邮件模块（10秒后自动退出）"
echo "cd cloudserver/login && timeout 10s python3 email_server.py"
echo ""

# ===== 4. 服务器启动测试 =====
echo -e "\n🌐 4. 服务器启动测试"
echo "在不同终端中分别执行："
echo ""
echo "# 终端1：启动服务器端"
echo "cd cloudserver/login && python3 server.py"
echo ""
echo "# 终端2：启动客户端"
echo "cd client/login && python3 server.py"
echo ""
echo "# 终端3：测试连接"
echo "curl http://localhost:5000/"
echo ""

# ===== 5. API功能测试 =====
echo -e "\n🔌 5. API功能测试"
echo "在服务器运行时执行："
echo ""
echo "# 测试邮件客户端状态"
echo "curl -X POST -H 'Content-Type: application/json' -d '{}' http://localhost:5000/api/check_email_client"
echo ""
echo "# 测试登录API（使用本地认证）"
echo "curl -X POST -H 'Content-Type: application/json' -d '{\"username\":\"admin\",\"password\":\"18b16e270de878f3\"}' http://localhost:5000/api/login"
echo ""

# ===== 6. 前端功能测试 =====
echo -e "\n🎨 6. 前端功能测试"
echo "在浏览器中测试："
echo ""
echo "# 打开客户端界面"
echo "http://localhost:5000/"
echo ""
echo "# 检查JavaScript控制台"
echo "按F12打开开发者工具，查看控制台输出"
echo ""

# ===== 7. 完整流程测试 =====
echo -e "\n🔄 7. 完整流程测试"
echo "按以下步骤测试完整流程："
echo ""
echo "步骤1：启动两个服务器"
echo "  - 服务器端: cd cloudserver/login && python3 server.py"
echo "  - 客户端: cd client/login && python3 server.py"
echo ""
echo "步骤2：在浏览器中打开 http://localhost:5000/"
echo ""
echo "步骤3：尝试邮件登录（如果邮箱配置正确）"
echo "  - 用户名：admin"
echo "  - 密码：123456"
echo ""
echo "步骤4：查看终端日志"
echo "  - 检查邮件发送和接收日志"
echo "  - 观察认证过程"
echo ""

# ===== 8. 故障排除 =====
echo -e "\n🔍 8. 故障排除命令"
echo "如果遇到问题，执行以下检查："
echo ""
echo "# 检查端口占用"
echo "netstat -tlnp | grep :5000"
echo ""
echo "# 检查进程"
echo "ps aux | grep python3"
echo ""
echo "# 检查日志"
echo "tail -f cloudserver/login/server.log 2>/dev/null || echo '日志文件不存在'"
echo ""
echo "# 重置环境"
echo "pkill -f 'python3 server.py'"
echo "pkill -f 'email_'"
echo ""

# ===== 9. 一键测试脚本 =====
echo -e "\n⚡ 9. 一键自动化测试"
echo "执行完整测试脚本："
echo ""
echo "chmod +x test_email_auth_system.sh"
echo "./test_email_auth_system.sh"
echo ""

echo "=================================="
echo "💡 提示："
echo "1. 首先确保邮箱授权码配置正确"
echo "2. 建议先进行基础检查，再测试邮件功能"
echo "3. 如果邮件功能不可用，系统会自动降级到本地认证"
echo "4. 查看控制台输出可以帮助诊断问题" 